### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by ndangu** [rmlor/alby_pawdrobe#17]
Citation for email validation function
SOURCE URL: https://stackoverflow.com/questions/46155/how-can-i-validate-an-email-address-in-javascript

FUNCTION DEFINITION
const validateEmail = (email) => {
  return email.match(
    /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
  );
};

const validate = () => {
  const $result = $('#result');
  const email = $('#email').val();
  $result.text('');

  if(validateEmail(email)){
    $result.text(email + ' is valid.');
    $result.css('color', 'green');
  } else{
    $result.text(email + ' is invalid.');
    $result.css('color', 'red');
  }
  return false;
}

$('#email').on('input', validate);

EXAMPLE USE
<label for="email">Enter email address</label>
<input id="email" type="email">

Citation for phone number validation 
SOURCE URL: https://stackoverflow.com/questions/4338267/validate-phone-number-with-javascript

/^(\()?\d{3}(\))?(-|\s)?\d{3}(-|\s)\d{4}$/

**Comment by Aydhiny** [comment]
can you assign this to me, I would love to help you :)
